#!/bin/sh

# Link dotfiles
for src in "$(pwd)"/customizations/.[!.]*; do
    [ -e "$src" ] && ln -fs "$src" "$HOME/"
done

# Link scripts
mkdir -p "$HOME/bin"
for src in "$(pwd)"/scripts/*; do
    [ -e "$src" ] && ln -fs "$src" "$HOME/bin/"
done